//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationProjetMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Emploi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Emploi()
        {
            this.ExamenParticuliers = new HashSet<ExamenParticulier>();
            this.TravSoumis = new HashSet<TravSoumi>();
        }
    
        public decimal idEmploi { get; set; }
        public System.DateTime dateEmbauche { get; set; }
        public Nullable<System.DateTime> dateFin { get; set; }
        public string soumis { get; set; }
        public decimal idEntreprise { get; set; }
        public decimal idTrav { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExamenParticulier> ExamenParticuliers { get; set; }
        public virtual Entreprise Entreprise { get; set; }
        public virtual Travailleur Travailleur { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TravSoumi> TravSoumis { get; set; }
    }
}
