//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationProjetMVC.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBIG3B8Entities : DbContext
    {
        public DBIG3B8Entities()
            : base("name=DBIG3B8Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Emploi> Emplois { get; set; }
        public virtual DbSet<Entreprise> Entreprises { get; set; }
        public virtual DbSet<ExamenParticulier> ExamenParticuliers { get; set; }
        public virtual DbSet<Risque> Risques { get; set; }
        public virtual DbSet<Travailleur> Travailleurs { get; set; }
        public virtual DbSet<TravSoumi> TravSoumis { get; set; }
        public virtual DbSet<TypeExaman> TypeExamen { get; set; }
    }
}
