//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationProjetMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Travailleur
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Travailleur()
        {
            this.Emplois = new HashSet<Emploi>();
        }
    
        public decimal idTrav { get; set; }
        public string nom { get; set; }
        public string ville { get; set; }
        public decimal codePostal { get; set; }
        public string rue { get; set; }
        public decimal numRue { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Emploi> Emplois { get; set; }
    }
}
